### ISSUE TITLE
Custom Postgres schema breaks followers

### ISSUE THREAD

**Issue by lxop** [pyeventsourcing/eventsourcing#242]
In `postgres.py:PostgresProcessRecorder:max_tracking_id()`, a statement is prepared:
```python
    def max_tracking_id(self, application_name: str) -> int:
        statement_name = self.max_tracking_id_statement_name
        self._prepare(statement_name, self.max_tracking_id_statement)
        ...
```
However the statement name is constructed as
```python
self.max_tracking_id_statement_name = f"max_tracking_id_{tracking_table_name}"
```
and when a custom Postgres schema is in use, the `tracking_table_name` has the format `schema_name.table_name`. Prepared statement names can't have a dot in them, so this fails, with `{SyntaxError}syntax error at or near "."`

I'm not an expert in prepared statements, but I suppose just running a `.replace(".", "_")` in the creation of `self.max_tracking_id_statement` would fix this (while retaining the schema name in the statement name to avoid collision).

**Comment by lxop** [comment]
Actually, I've just found that using `.replace(".", "_")` can cause non-unique statement names. This is because statement names are truncated at 63 characters (by default, at least) because they are an identifier. Putting the schema name first chews up valuable real-estate. Since statements are local to a session, would the schema name actually be necessary? If not, `.split(".")[-1]` might be more appropriate.

**Comment by johnbywater** [comment]
@lxop As discussed on Slack, thanks for raising this issue.

I think I fixed both aspects in https://github.com/pyeventsourcing/eventsourcing/commit/88fe8bbe0feeaceca6f6cab0ddb6852db3381f99.

Let me know if it's working for you now? Please note, since this issue was raised, I have changed several things in the postgres module, especially adding a connection pool which still needs more work. In the meantime, please set environment variables 'POSTGRES_POOL_MIN_CONN' and 'POSTGRES_POOL_MAX_CONN' to a suitable number.

**Comment by johnbywater** [comment]
@lxop I have finished the new connection pool. As [documented](https://eventsourcing.readthedocs.io/en/latest/topics/persistence.html#postgresql-module), the new named for the environment variables mentioned above are `POSTGRES_POOL_SIZE` and `POSTGRES_MAX_OVERFLOW`. See also `POSTGRES_POOL_TIMEOUT`.
