### ISSUE TITLE
Support for rabbitmq

### ISSUE THREAD

**Issue by Elter71** [pyeventsourcing/eventsourcing#254]
Hi, do you have plans to add rabbitmq support?

**Comment by johnbywater** [comment]
Hi @Elter71! Thanks for asking about rabbitmq. How would you like rabbitmq to be supported?

**Comment by Elter71** [comment]
Hi, I would like to use rabbitmq as an events source. I'm happy to help in implementing it ☺️

**Comment by johnbywater** [comment]
Are you wanting to process messages from rabbitmq in through an event sourcing application? or are you wanting to use rabbitmq as as event store?

**Comment by johnbywater** [comment]
Hi @Elter71, just wondering if you are still interested in this? ☺️

**Comment by adam-mrozik** [comment]
I am not the author, but using RabbitMQ as an event store would be nice. I guess it would be an equivalent of current EventStoreDB implementation.


Also, maybe a little offtopic (I can start new topic if needed), but what would be your recommendation for a production-grade event driven system, considering I am not skewed towards any event-store, and using Flask/SQLAlchemy?

Since I work on multiple kubernetes clusters, I need to also think about this event store being accessible from different clusters. Ideally some kind of centralized DB that stores all the events.

I am basically torn between using raw SQLAlchemy adaptation and EventStoreDB. As I understand, the difference will be basically visibility and fine-grained control that is provided by EventStoreDB. But, SQLAlchemy adaptation would mean I can just reuse my current PG DB, with just a separate table for storing all events. Not sure how it scales though.
Third option is to just use raw package and adapt even handling to a system of my choice like RabbitMQ. But obviously would rather reuse what has been already done.


If you have any guidance or intuition around these, it would be very helpful. I would be keen to adopt `eventsourcing`, but still am torn about the proper strategy :)

**Comment by adam-mrozik** [comment]
Thanks ! Was just reading through it. I have a couple of questions though.

1. Lets say I currently have app which has user accounts and each user can have multiple profiles. So, I will create aggregate called Account, which will contain account_information and list of profiles. In tutorials I see you are getting current states from repository. However, because I have a lot of systems editing my data and even sometimes users editing it directly with SQL, I cannot simply rely (yet, at least), on reconstructing the object based on the recorded events. I need to always call my current models to get the current states. So, there is a lot of functionality of eventsourcing, which I will simply not use.
I guess my main goal is to construct some CQRS system like described here: https://www.cosmicpython.com/book/chapter_12_cqrs.html

so, essentially have the system controlled by Messagebus which records events and side-effects and acts on them accordingly.
```
EVENT_HANDLERS = {
    events.Allocated: [publish_allocated_event, add_allocation_to_read_model],
    events.Deallocated: [remove_allocation_from_read_model, reallocate],
    events.OutOfStock: [send_out_of_stock_notification],
}  # type: Dict[Type[events.Event], List[Callable]]

COMMAND_HANDLERS = {
    commands.Allocate: allocate,
    commands.CreateBatch: add_batch,
    commands.ChangeBatchQuantity: change_batch_quantity,
}  # type: Dict[Type[commands.Command], Callable]
```

`eventsourcing` seems like a package that does this, but also much more, so I am trying to gain some intuition if it is the right tool for me. 
Also, thanks for quick responses here, really appreciate that

**Comment by johnbywater** [comment]
Sorry for the delay, I just had to read that book through again to refresh my memory,and check again what it does and doesn't say...

Basically, the approach of "message processing" mobilized in that book is shot through with dual writing. No amount of extra coding can remedy the situation. The consequences are excused with the phrase "distributed systems are hard" but the actual issue isn't identified.

I like Harry very much, and if you follow the logic of that book forward, beyond the scope of the book, eventually you end up with exactly what this library does. But just as the book progresses by subsequent chapters deprecating the proposals of previous chapters, in the end the common and conventional "message processing" approach using a message bus, which is the central idea mobilized by Bob in this book, needs to be deprecated. And not much remains.

That book mentions MADE.com several times, and indeed reflects the architecture at MADE.com. MADE.com failed as a business last year. Not actually because of the software architecture. But nevertheless their software architecture suffered from dual writing issues. I suspected it did from reading this book, and my suspicions were verified several years ago in some private discussions with some other senior technology people who worked there. I don't really care about their code. I'm just trying to be objective about the techniques. 

Avoiding the weakness of the "message processing" approach in distributed systems is really what this library is focussed on. It needs to be provided for in a way that isn't described in that book. And afterwards, you end up playing a different game, one that doesn't need to involve message buses at all. And in fact message buses just mess it all up. This has been generally understandable since at least 2013, but still it isn't widely understood, and so it's perhaps necessary to be quite definite and straightforward about this now.

That book mentions that in the case of shipping furniture, it may happen that an item falls off the back of a truck, and so you need a way to refund customers, and so it's okay for the code to result in other situations created by the code where you also need to refund customers. Fair enough, but that doesn't explain how to make a distributed system that is in fact reliable in the consequential resulting state, after it has the opportunity to become eventually consistent. That is, it doesn't explain how to avoid the inevitable operational failures of components leading to a situation that is forever inconsistent. Forever that is, until somebody goes through the log files and figures out a manual correction (I'm just repeating what the book said).

Not everyone is selling furniture. By the same token, not everyone needs to care about making a reliable distributed system. But I think it's better to understand how you can, and then degrade away from that high point, to accomplish other goals, if those goals justify the degradation. And otherwise just do things in a way that doesn't suffer unnecessarily from issues that haven't been grasped, as if that's just the way it goes with distributed systems.

The technique you need to avoid dual writing in the execution of commands is to make the "bounded content control the messaging." But you also need to avoid dual writing in the consumption of event notifications. This means recording the "messages" (the domain events) in the same transaction along with new state. It means that these messages must be appended to a "totally ordered" sequence. And it means when processing these "messages" that new state is recorded atomically along with the position of the message in the sequence, so that processing can resume from that recorded position, and so that the processing has "exactly once" semantics from the point of view of looking at downstream recorded state.

So I guess the first step in your situation is to work towards each mutating write to the database to include the writing of a sequenced notification. Without this, I don't think you can really expect to achieve very much satisfaction.

If you were starting from scratch, the easiest thing is to just write the event notifications, and not the snapshot of the current state, and to have two indexes: one that selects the aggregate events in order to reconstruct an aggregate, and one that selects from the total order sequence to propagate the state of the collection of aggregates in the domain model.

But if you start by giving your snapshots version numbers, as Bob and Harry describe in that book, and you write event notifications along with these snapshots, then you can switch over later to doing event sourcing, by using those snapshots as the initial state from which a sequence of events is applied to reconstruct current state. In this way you can migrate from your current situation to a much simpler, more maintainable, more reliable, body of code. And I think then you will accomplish the depth of satisfaction I am sure you seek.

I wrote a lot about this in v8 of the docs, and haven't yet brought this text forward into the docs for v9. So I thought it would be good to just write some of this out here.

https://eventsourcing.readthedocs.io/en/v8.3.0/topics/notifications.html

https://eventsourcing.readthedocs.io/en/v8.3.0/topics/projections.html

https://eventsourcing.readthedocs.io/en/v8.3.0/topics/process.html

**Comment by johnbywater** [comment]
Sounds great @adam-mrozik! We're all just trying to help people like you find a good way forward.
