### ISSUE TITLE
Is it necessary to re-hydrate an aggregate to check it exists in a repository?

### ISSUE THREAD

**Issue by bibz** [pyeventsourcing/eventsourcing#256]
`eventsourcing.application.Repository.__contains__` reconstructs the _complete_ history of an aggregate to answer whether the aggregate exists in the repository or not.
Since the repository is not able to delete an aggregate, could it make sense to limit the aggregate events fetching to the initial event to improve performance?

Basically applying the following patch:
```diff
diff --git a/eventsourcing/application.py b/eventsourcing/application.py
index 08abc52e..85a46b52 100644
--- a/eventsourcing/application.py
+++ b/eventsourcing/application.py
@@ -384,7 +384,7 @@ class Repository:
         Tests to see if an aggregate exists in the repository.
         """
         try:
-            self.get(aggregate_id=item)
+            self.get(aggregate_id=item, version=1)
         except AggregateNotFound:
             return False
         else:
```

My use-case is to rely on `aggregate in self.repository` liberally in my application, _assuming the aggregate would not get hydrated for nothing_ if it is present in the repository.

**Comment by johnbywater** [comment]
Good question @bibz, as always!

It's done this way because an aggregate might define a "deleted" event that has a `mutate()` method that returns `None`.

If you know you don't have any such things in your domain model, and you want to use the `in` operator, then I would suggest overriding the `Repository` method and instead just see if it can get one stored event from the recorder? And don't bother running it through a projection, or using the mapper to convert to a domain event? That's likely the fastest thing to do? :-)

**Comment by bibz** [comment]
Aha! Thanks for bringing the mutation behaviour into the light, I didn't think about using it that way.

Then it is clear we need the default behaviour, as usual you are two steps ahead!

**Comment by bibz** [comment]
@johnbywater it was, of course, as easy as you made it look.

I implemented a quick subclass at https://git.sr.ht/~docbibi/pyeventsourcing-contrib/commit/ea7b85ea7caaa5c644df370c1557e40f068e7c65. Will add tests and move on.

**Comment by johnbywater** [comment]
You probably know already, there's a section in the docs about "discarded" events. I just separated it out under a new heading:
https://eventsourcing.readthedocs.io/en/latest/topics/domain.html#discarded-events
