### ISSUE TITLE
Suggested approach to Entities in 9.x?

### ISSUE THREAD

**Issue by harlanji** [pyeventsourcing/eventsourcing#257]
Hi, I'm kicking the tires of the project and it's nice sofar. New to formalized ES as well. I found some Entity stuff that's been removed in 9.x, only after building a little test case with a list of 'value objects' on the Aggregate, and searched around in the issues, docs and code of 9.2; found no mention of Entities. The existing examples and docs have been great so-far, surprised to see the idea missing. What I saw did look useful, ChangedAttribute, versioning, and the like.

My test is a Receipt aggregate as a dataclass with a List[LineItem] property, the latter also a dataclass. Test passes, all good, made it prior to looking into whether there's a baked in idea of Entities. Made [this Gist with my approach](https://gist.github.com/harlanji/8a4cd0adac32d626d052034bea560e08), storing value object dataclasses as dicts and restoring via dacite in a Transcoding.

I'm having trouble remembering if Entities have identities or not and all that distinguishes them from a value object, but the code that I found in this repo had them with an ID (the test_entity.py suite), so I guess they have identities. It may not be the case that I need an Entity right now, just trying to touch all the bases. But if I were to need one, what would be the suggested approach now in 9.x? Thanks.

**Comment by johnbywater** [comment]
Hi @harlanji, thanks for your interest in this project, and for opening this issue.

What has been removed that you are missing? Can you point me to exactly what you have been looking at, just so I'm clear?

The basic idea of an entity in DDD is that it has a unique identity that doesn't change, and attributes that do change. Value objects generally don't have a unique identity and are unchanging. You can just code these as simple Python objects. The difference with an aggregate is that it is an entity that controls a cluster of entities and value objects. This responsibility involves making decisions, a sequence of decisions, which can be made explicit as event objects. To make an event sourced aggregate, these event objects will be persisted and used to reconstruct the aggregate. So, basically, there is nothing in this library which is needed to support entities, because non-aggregate entities are controlled by the aggregate, which is supported. In fact, custom classes will need to be transcoded. But I backed off from trying to support this in general, because it was becoming messy without becoming complete. And transcoding is most probably something users need to take responsibility for. Is it the more extensive transcoding support which you are missing?
