### ISSUE TITLE
Additional examples

### ISSUE THREAD

**Issue by d-m** [pyeventsourcing/eventsourcing#262]
Are there any examples of using this library:

* with multiple processes (`Application` instances) reading events off an event bus
* with multiple `Aggregate` classes
* for creating and storing read-only projections
* to integrate with external APIs

It looks like there were some examples of this going back to v6 but the library has changed pretty significantly since then.

Happy to help create this as well, although I'm new to this library and the architecture pattern. For example, can one `Application` instance work with multiple distinct `Aggregate` classes? Should it? What I've read of DDD seems to suggest that each aggregate should have a distinct repository.

**Comment by johnbywater** [comment]
Hi @d-m, sorry for the delay in replying to your questions. I was just away having an extended summer break. I'm back now.

The answer to the question about having more than one type of aggregate in an application: the answer is definitely yes you can do this. There's no way in which DDD suggests a bounded context should have only one type of aggregate. The reason that a repository was associated with one type of aggregate was basically because in the original non-event sourced conception of domain models, the repository pattern essentially encapsulated one table in a database. But with event sourcing, firstly there is one table for all events (so the essential reality of a repository encapsulating a table is continued), and secondly in practice there's really nothing to be gained by having many repositories to retrieve event sourced aggregates. We all tried doing that in the early days, but quite quickly realised it was just redundant code, and moved to having a single repository for all aggregates in a bounded context. By the way, an application's domain model in this library roughly corresponds to a bounded context in DDD. However, the notion of a bounded context is sometimes defined as the extent of a ubiquitous language. And so it may be that you have several applications that have an aggregates all effectively within the same ubiquitous language. The more important consideration is that an application in this library will have all its domain events in a serial order in its application sequence. And events in different applications will be in different application sequences, and so there won't be any serial ordering across the events of aggregates in different applications. Hope that's clear! :)

Regarding docs for read-only projections, and examples of more complex domain models... these are frequently asked questions, and it's simply true that these things don't exist. So if you would like to produce such things, or contribute to such things, that would be great!

**Comment by johnbywater** [comment]
Hey @d-m,

There's a new "system" example here which I created today:
https://eventsourcing.readthedocs.io/en/latest/topics/examples/content-management-system.html

It has "multiple processes (Application instances)", "multiple Aggregate classes", and "creating and storing read-only projections".

Let me know what you think?

What do you mean by "to integrate with external APIs"? You can just do this, but the "exactly once" semantics are probably not going to be supported. Nevertheless, it's possible to do it with "at least once" semantics in a `policy()` function and if you combine this with an "idempotent" API then you can more or less get the same thing. I'm not sure what the library could do to help with this, but yes an example might be useful.
